# Generated by Django 3.2.7 on 2021-09-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FD', 'FOOD'), ('SK', 'SNACKS'), ('CL', 'CLOTHING'), ('OS', 'ONLINE_SHOPPING')], default='FD', max_length=2)),
                ('price', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
