# Generated by Django 3.2.7 on 2021-09-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fund',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
