# Generated by Django 3.2.7 on 2021-09-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='fund',
            field=models.CharField(default='so', max_length=32),
            preserve_default=False,
        ),
    ]
