# Generated by Django 3.2.7 on 2021-09-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_auto_20210926_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='account',
        ),
    ]
