# Generated by Django 3.2.7 on 2021-09-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20210926_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
